version: "3.8"

services:
  django:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    image: django_image
    container_name: django
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"
    command: /start

  react:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    image: react_image
    container_name: react
    volumes:
      - ./src:/src
    working_dir: /src/frontend
    ports:
      - "3000:3000"
    command: /start