# Generated by Django 4.0.6 on 2022-07-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ballots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_vote', models.BooleanField(blank=True, default=False)),
                ('cat_vote', models.BooleanField(blank=True, default=False)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
